#!/bin/bash
#SBATCH --job-name=MacsPeakCalling
#SBATCH --partition=batch
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ry00555@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=90gb
#SBATCH --time=4:00:00
#SBATCH --output=../MacsPeakCalling.%j.out
#SBATCH --error=../MacsPeakCalling.%j.err

cd $SLURM_SUBMIT_DIR


OUTDIR="/scratch/ry00555/RNASeqPaper/SortedBamFiles"


for bam in $(find . -name "*.bam"); do
    bai="${bam}.bai"
    if [ ! -f "$bai" ]; then
        echo "Missing index for: $bam"
    fi
done

module load MACS3
