#!/bin/bash
#SBATCH --job-name=zl_mapChIPseq
#SBATCH --partition=batch
#SBATCH --mail-type=ALL
#SBATCH --mail-user=zlewis@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=50gb
#SBATCH --time=08:00:00
#SBATCH --output=MapCutAndRun.%j.out
#SBATCH --error=MapCutAndRun.%j.err

cd $SLURM_SUBMIT_DIR

#read in variables from the config file ($threads, $FASTQ, $OUTDIR, )
source ./config.txt

#process reads using trimGalore

ml Trim_Galore/0.6.5-GCCcore-8.3.0-Java-11-Python-3.7.4
trim_galore --paired --length 20 --fastqc --gzip -o ${OUTDIR}/TrimmedReads ${FASTQ}/*fastq\.gz

FILES="${OUTDIR}/TrimmedReads/*R1_001_val_1\.fq\.gz" #Don't forget the *

mkdir "${OUTDIR}/SortedBamFiles"
mkdir "${OUTDIR}/BigWigs"
mkdir "${OUTDIR}/Peaks"
#mkdir "$OUTDIR/HomerTagDirectories"
#mkdir "$OUTDIR/TdfFiles"
#
#Iterate over the files
for f in $FILES
do
#
# 	#Examples to Get Different parts of the file name
# 		#See here for details: http://tldp.org/LDP/abs/html/refcards.html#AEN22664
		#${string//substring/replacement}
# 		#dir=${f%/*}
		
	file=${f##*/}
	#remove ending from file name to create shorter names for bam files and other downstream output
	name=${file//_S*_L001_R1_001_val_1\.fq\.gz/}

#
# 	# File Vars
# 	#use sed to get the name of the second read matching the input file
	read2=$(echo "$f" | sed 's/R1_001_val_1\.fq\.gz/R2_001_val_2\.fq\.gz/g')
	#variable for naming bam file
 	bam="${OUTDIR}/SortedBamFiles/${name}.bam"
	#variable name for bigwig output
	bigwig="${OUTDIR}/BigWigs/${name}"
#
#
ml SAMtools/1.9-GCC-8.3.0
ml BWA/0.7.17-GCC-8.3.0
#
bwa mem -M -v 3 -t $THREADS $GENOME $f $read2 | samtools view -bhSu - | samtools sort -@ $THREADS -T $OUTDIR/SortedBamFiles/tempReps -o "$bam" -

samtools index "$bam"

############################
# # #deeotools

ml deepTools/3.3.1-intel-2019b-Python-3.7.4
# #use these parameters for ChIP data
bamCoverage -p $THREADS $BIN --smoothLength 50 -of bigwig -b "$bam" -o "${bigwig}.bin_{$BIN}.smooth_{$SMOOTH}{$MN}.bw"



ml MACS2/2.2.7.1-foss-2019b-Python-3.7.4

macs2 callpeak -t $OUTDIR/SortedBamFiles/121-2_ChIP_JE24646_a_rep1.bam -c $OUTDIR/SortedBamFiles/121-1_ChIP_JE24646_input_a_rep1.bam -f BAMPE -n Rep1.macs.peak --outdir $OUTDIR/Peaks -g 5000000 -B -q 0.001

macs2 callpeak -t $OUTDIR/SortedBamFiles/121-4_ChIP_JE24646_b_rep2.bam -c $OUTDIR/SortedBamFiles/121-3_ChIP_JE24646_input_b_rep2.bam -f BAMPE -n Rep2.macs.peak --outdir $OUTDIR/Peaks -g 5000000 -B -q 0.001

macs2 callpeak -t $OUTDIR/SortedBamFiles/121-6_ChIP_JE24646_c_rep3.bam -c $OUTDIR/SortedBamFiles/121-5_ChIP_JE24646_input_c_rep3.bam -f BAMPE -n Rep3.macs.peak --outdir $OUTDIR/Peaks -g 5000000 -B -q 0.001


#Call consensus Peaks

#the following command was used to build consensus peaks from unfiltered MACS2 output. Fold change data were generated by filtering MACS2 output based on fold change and then running a similar mspc command on filtered output. 

~/bin/mspc/mspc -i $OUTDIR/Peaks/Rep*.macs.peak_peaks.xls -r bio -w 1e-4 -s 1e-8 -p /scratch/zlewis/myConfig.json

done



#### homer was tested but not used due to high stringency that removed all but 5 peaks

###########################
# #create a homer tag directory
# ~/bin/homer/bin/makeTagDirectory $OUTDIR/HomerTagDirectories/$file -keepOne -mis 0 $sorted.bam
############################

#findPeaks <tag directory> -style <factor | histone> -o auto -i <control tag directory>
#
# #rep 1
#  ~/bin/homer/bin/findPeaks /scratch/zlewis/Run121_AnastaciaOut/HomerTagDirectories/Sorted_121-2_ChIP_JE24646_a_rep1_S2_L001_R1_001.fastq.gz.bam -style factor -o $OUTDIR/Peaks/Rep1.peaks -i /scratch/zlewis/Run121_AnastaciaOut/HomerTagDirectories/Sorted_121-1_ChIP_JE24646_input_a_rep1_S1_L001_R1_001.fastq.gz.bam
#
# #rep 2
# ~/bin/homer/bin/findPeaks /scratch/zlewis/Run121_AnastaciaOut/HomerTagDirectories/Sorted_121-4_ChIP_JE24646_b_rep2_S4_L001_R1_001.fastq.gz.bam -style factor -o $OUTDIR/Peaks/Rep2.peaks -i /scratch/zlewis/Run121_AnastaciaOut/HomerTagDirectories/Sorted_121-3_ChIP_JE24646_input_b_rep2_S3_L001_R1_001.fastq.gz.bam
#
# #rep 3
# ~/bin/homer/bin/findPeaks /scratch/zlewis/Run121_AnastaciaOut/HomerTagDirectories/Sorted_121-6_ChIP_JE24646_c_rep3_S6_L001_R1_001.fastq.gz.bam -style factor -o $OUTDIR/Peaks/Rep3.peaks -i /scratch/zlewis/Run121_AnastaciaOut/HomerTagDirectories/Sorted_121-5_ChIP_JE24646_input_c_rep3_S5_L001_R1_001.fastq.gz.bam


